### ISSUE TITLE
App crash on launch on some devices

### ISSUE THREAD

**Issue by jake-moritz-trifecta** [forcedotcom/SalesforceMobileSDK-Android#2013]
We've been experiencing app crashes when our app is opened. The issue seems related to  https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1963, despite having upgraded to the SF Mobile SDK version that should have fixed this issue. We have not been able to reproduce the issue with local builds, this only happens when our app is built through our Azure DevOps pipeline. This crash was not reproduce-able on identical devices with the same version of Android, so it may be specific to the  exact Galaxy S8 and Pixel 3a devices we have in office. Our app has multiple variants, where things like app name, icon, and other resources are changed. This bug is only occurring for one specific variant of the app. We would like some advice as to what could be causing this issue and how to proceed.

1. Version of Mobile SDK Used: 7.3.0
2. Issue found in Native App or Hybrid App: hybrid
3. OS Version: Android 9.0, Android 7.0
4. Device: Samsung Galaxy S8 (Android 7.0), Google Pixel 3a (Android 9.0)
5. Steps to reproduce: 

- Open our app

6. Actual behavior: 

- App does not crash

7. Expected Behavior:

- App crashes

8. Error Log:

```
2019-11-26 11:09:24.719 16489-16489/? D/SalesforceHybridSDKManager: Setting up global store using config found in www/globalstore.json
2019-11-26 11:09:25.046 16489-16489/com.mobile.qa E/Encryptor: Error during asymmetric decryption
    javax.crypto.IllegalBlockSizeException
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
        at javax.crypto.Cipher.doFinal(Cipher.java:2055)
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithPrivateKey(Encryptor.java:365)
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithRSABytes(Encryptor.java:318)
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithRSA(Encryptor.java:299)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:227)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:90)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:79)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateEncryptionKey(SalesforceKeyGenerator.java:208)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:105)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getEncryptionKey(SalesforceSDKManager.java:1126)
        at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:160)
        at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:142)
        at com.salesforce.androidsdk.phonegap.app.SalesforceHybridSDKManager.setupGlobalStoreFromDefaultConfig(SalesforceHybridSDKManager.java:172)
        at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onCreate(SalesforceDroidGapActivity.java:111)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.security.KeyStoreException: Unknown error
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:839)
        at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
        at javax.crypto.Cipher.doFinal(Cipher.java:2055) 
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithPrivateKey(Encryptor.java:365) 
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithRSABytes(Encryptor.java:318) 
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithRSA(Encryptor.java:299) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:227) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:90) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:79) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateEncryptionKey(SalesforceKeyGenerator.java:208) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:105) 
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getEncryptionKey(SalesforceSDKManager.java:1126) 
        at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:160) 
        at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:142) 
        at com.salesforce.androidsdk.phonegap.app.SalesforceHybridSDKManager.setupGlobalStoreFromDefaultConfig(SalesforceHybridSDKManager.java:172) 
        at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onCreate(SalesforceDroidGapActivity.java:111) 
        at android.app.Activity.performCreate(Activity.java:7144) 
        at android.app.Activity.performCreate(Activity.java:7135) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-11-26 11:09:25.049 16489-16489/com.mobile.qa E/SalesforceKeyGenerator: Exception thrown while getting encryption key
    java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.nio.charset.Charset)' on a null object reference
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateEncryptionKey(SalesforceKeyGenerator.java:209)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:105)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getEncryptionKey(SalesforceSDKManager.java:1126)
        at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:160)
        at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:142)
        at com.salesforce.androidsdk.phonegap.app.SalesforceHybridSDKManager.setupGlobalStoreFromDefaultConfig(SalesforceHybridSDKManager.java:172)
        at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onCreate(SalesforceDroidGapActivity.java:111)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-11-26 11:09:25.056 16489-16489/com.mobile.qa D/SalesforceHybridSDKManager: Setting up global syncs using config found in www/globalsyncs.json
2019-11-26 11:09:25.174 16489-16489/com.mobile.qa E/Encryptor: Error during asymmetric decryption
    javax.crypto.IllegalBlockSizeException
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
        at javax.crypto.Cipher.doFinal(Cipher.java:2055)
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithPrivateKey(Encryptor.java:365)
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithRSABytes(Encryptor.java:318)
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithRSA(Encryptor.java:299)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:227)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:90)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:79)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateEncryptionKey(SalesforceKeyGenerator.java:208)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:105)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getEncryptionKey(SalesforceSDKManager.java:1126)
        at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:160)
        at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:142)
        at com.salesforce.androidsdk.phonegap.app.SalesforceHybridSDKManager.setupGlobalSyncsFromDefaultConfig(SalesforceHybridSDKManager.java:199)
        at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onCreate(SalesforceDroidGapActivity.java:112)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.security.KeyStoreException: Unknown error
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:839)
        at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
        at javax.crypto.Cipher.doFinal(Cipher.java:2055) 
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithPrivateKey(Encryptor.java:365) 
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithRSABytes(Encryptor.java:318) 
        at com.salesforce.androidsdk.analytics.security.Encryptor.decryptWithRSA(Encryptor.java:299) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateUniqueId(SalesforceKeyGenerator.java:227) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:90) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getUniqueId(SalesforceKeyGenerator.java:79) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateEncryptionKey(SalesforceKeyGenerator.java:208) 
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:105) 
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getEncryptionKey(SalesforceSDKManager.java:1126) 
        at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:160) 
        at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:142) 
        at com.salesforce.androidsdk.phonegap.app.SalesforceHybridSDKManager.setupGlobalSyncsFromDefaultConfig(SalesforceHybridSDKManager.java:199) 
        at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onCreate(SalesforceDroidGapActivity.java:112) 
        at android.app.Activity.performCreate(Activity.java:7144) 
        at android.app.Activity.performCreate(Activity.java:7135) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-11-26 11:09:25.175 16489-16489/com.mobile.qa E/SalesforceKeyGenerator: Exception thrown while getting encryption key
    java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.nio.charset.Charset)' on a null object reference
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.generateEncryptionKey(SalesforceKeyGenerator.java:209)
        at com.salesforce.androidsdk.security.SalesforceKeyGenerator.getEncryptionKey(SalesforceKeyGenerator.java:105)
        at com.salesforce.androidsdk.app.SalesforceSDKManager.getEncryptionKey(SalesforceSDKManager.java:1126)
        at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:160)
        at com.salesforce.androidsdk.smartstore.app.SmartStoreSDKManager.getGlobalSmartStore(SmartStoreSDKManager.java:142)
        at com.salesforce.androidsdk.phonegap.app.SalesforceHybridSDKManager.setupGlobalSyncsFromDefaultConfig(SalesforceHybridSDKManager.java:199)
        at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onCreate(SalesforceDroidGapActivity.java:112)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-11-26 11:09:25.186 16489-16489/? D/AndroidRuntime: Shutting down VM
2019-11-26 11:09:25.187 16489-16489/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mobile.qa, PID: 16489
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mobile.qa/com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity}: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;
        at net.sqlcipher.database.SQLiteCompiledSql.native_compile(Native Method)
        at net.sqlcipher.database.SQLiteCompiledSql.compile(SQLiteCompiledSql.java:91)
        at net.sqlcipher.database.SQLiteCompiledSql.<init>(SQLiteCompiledSql.java:64)
        at net.sqlcipher.database.SQLiteProgram.<init>(SQLiteProgram.java:89)
        at net.sqlcipher.database.SQLiteQuery.<init>(SQLiteQuery.java:48)
        at net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:60)
        at net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:2012)
        at net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1898)
        at net.sqlcipher.database.SQLiteDatabase.keyDatabase(SQLiteDatabase.java:2647)
        at net.sqlcipher.database.SQLiteDatabase.openDatabaseInternal(SQLiteDatabase.java:2577)
        at net.sqlcipher.database.SQLiteDatabase.openDatabase(SQLiteDatabase.java:1243)
        at net.sqlcipher.database.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:1318)
        at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:166)
        at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:135)
        at net.sqlcipher.database.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:131)
        at com.salesforce.androidsdk.smartstore.store.SmartStore.getDatabase(SmartStore.java:234)
        at com.salesforce.androidsdk.smartsync.manager.SyncManager.getInstance(SyncManager.java:151)
        at com.salesforce.androidsdk.smartsync.config.SyncsConfig.createSyncs(SyncsConfig.java:124)
        at com.salesforce.androidsdk.phonegap.app.SalesforceHybridSDKManager.setupSyncsFromConfig(SalesforceHybridSDKManager.java:218)
        at com.salesforce.androidsdk.phonegap.app.SalesforceHybridSDKManager.setupGlobalSyncsFromDefaultConfig(SalesforceHybridSDKManager.java:199)
        at com.salesforce.androidsdk.phonegap.ui.SalesforceDroidGapActivity.onCreate(SalesforceDroidGapActivity.java:112)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by bhariharan** [comment]
@jake-moritz-trifecta Based on your description and the stack trace, it appears that this may be due to a corrupted `Keystore` in the 2 specific devices that you have. Perhaps you could you try factory resetting those devices to see if that fixes the `Keystore` issue? If not, there's not much that can be done - this is an OS-level call that's failing due to device corruption.

**Comment by jake-moritz-trifecta** [comment]
@bhariharan I reset both of our devices and we are no longer experiencing the issue. Thank you.

**Comment by jake-moritz-trifecta** [comment]
We are now seeing this issue occur in production. Is there a reason how the Android Keystore could become corrupted in this way?

**Comment by bhariharan** [comment]
@jake-moritz-trifecta There's a known issue with `Keystore` and `BouncyCastle` on some older devices. It appears this issue has been fixed in newer versions of `Android`, especially since newer versions have removed `BouncyCastle` and replaced it with `Conscrypt` instead. What's the frequency of occurrence of this issue in production? Are you able to establish any patterns, i.e. device type, OS versions, etc.? I can investigate a bit more, but there might not be much we can do. Perhaps we could evaluate the usage from within the app too, since we don't appear to see this issue on any other apps built on Mobile SDK.

**Comment by jake-moritz-trifecta** [comment]
@bhariharan We have reports of this happening twice in production so far, both times on separate Google Pixel 2 XLs running Android 10.

**Comment by jake-moritz-trifecta** [comment]
@bhariharan One user performed a factory reset on their device and are still experiencing the app crash. What details can we provide about our usage of the Salesforce Mobile SDK that could be helpful here?

**Comment by bhariharan** [comment]
@jake-moritz-trifecta Could you give me more information about your app's architecture? A few questions:
- From the stack trace, it appears to be a hybrid app. Is it `hybrid_local` or `hybrid_remote`?
- Which parts of the SDK do you use, i.e. do you use `SmartSync` or `SmartStore`?
- Also, how did you create your app - did you generate a fresh app from `forcedroid@7.3.0` or retrofit the new SDK into an older version of your app?
- Are the users that are facing the crash upgrading from an older version of the app, or attempting the use a fresh installation of the app?

**Comment by jake-moritz-trifecta** [comment]
@bhariharan 

* Our app is not created using `forcedroid`. It is an `Ionic/Cordova` app that uses the `Salesforce Mobile SDK Cordova` and `forcejs` for user authentication and consuming Apex REST APIs. 
* We do not specifically/directly use `SmartSync` or `SmartStore`
* I'm assuming `hybrid_local/hybrid_remote` has to do with `forcedroid`? Otherwise I'm not sure what these mean
* I believe this occurred when the user did a fresh installation

**Comment by bhariharan** [comment]
> Our app is not created using `forcedroid`.

Sorry, I meant `forcehybrid`, our `npm` package for `Cordova` apps. Apps generated using `forcehybrid` are created from our templates that have the right API calls to initialize the SDK and set things up correctly. Did you use the `ionic` CLI and add our plugin through it? If so, there might be some post-install steps missing.

> I'm assuming `hybrid_local/hybrid_remote` has to do with `forcedroid`? Otherwise I'm not sure what these mean.

This basically indicates whether the hybrid assets that the app uses are hosted locally or remotely.
- `hybrid_local` -> HTML/CSS/JS hosted locally within the app.
- `hybrid_remote` -> Nothing hosted within the app. The app points to a `Salesforce` page that is loaded within the web view.
Sounds like yours is a `hybrid_local` app since you're using `force.js` and making REST API calls.

**Comment by jake-moritz-trifecta** [comment]
We use the Ionic CLI and add the SF Mobile SDK Cordova plugin through it. We use the included post-install Node script in our build pipeline and can confirm it is being run for each build. Based on your definition, our app is `hybrid_local`.

**Comment by jake-moritz-trifecta** [comment]
@bhariharan Is there any more info we can provide here?

**Comment by bhariharan** [comment]
There's not a whole lot that we can do, unfortunately. The crux of the issue is this:
```
Caused by: android.security.KeyStoreException: Unknown error
```
There are known issues with some device implementations of `Keystore`. Unfortunately, these are vendor dependent and there's not much we can do.

**Comment by wmathurin** [comment]
Closing since the root of the problem does not seem to be the Mobile SDK.

**Comment by pbergner** [comment]
@jake-moritz-trifecta were ever you able to find a resolution to this issue?

**Comment by jake-moritz-trifecta** [comment]
> @jake-moritz-trifecta were ever you able to find a resolution to this issue?

No, but we have not had this issue popup recently. It seems to be very rare. I assume it's due to use not using `forcedroid/forcehybrid` to generate our application.

**Comment by jake-moritz-trifecta** [comment]
> @jake-moritz-trifecta were ever you able to find a resolution to this issue?

We are continuing to see this issue intermittently. Have you found a solution?

**Comment by BriaanSz** [comment]
@jake-moritz-trifecta I've got the same issue, did you found how to solve it?

**Comment by jake-moritz-trifecta** [comment]
> @jake-moritz-trifecta I've got the same issue, did you found how to solve it?

No, I haven't. Furthermore it appears using this plugin via Ionic is not supported either, so I'm not sure how much help we will be getting. I am seeing https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin/issues/533 this issue more often now.

**Comment by BriaanSz** [comment]
@jake-moritz-trifecta for me this only happens when I generate the signed apk for production, with the debug apk it works fine

**Comment by BriaanSz** [comment]
is there a workaround to use the app?

**Comment by AxesandGrinds** [comment]
I'm having this issue on a Native Android App. Same crash. Using Java Salesforce SDK 9.1.0. This is a problem with the Salesforce SDK and you know it. And users have been complaining for years and you keep saying there's nothing you can do. Doesn't that show you that it's a big issue? It's crashing for both Debug and Release APK for the Nord OnePlus N10 and various client phones.
